python -m preprocess_hanhwa.dawndusk_clear_split
python -m preprocess_hanhwa.dawndusk_clear
python -m preprocess_hanhwa.dawndusk_cloudy
python -m preprocess_hanhwa.dawndusk_foggy
python -m preprocess_hanhwa.dawndusk_overcast
python -m preprocess_hanhwa.dawndusk_rainy
python -m preprocess_hanhwa.daytime_clear_split
python -m preprocess_hanhwa.daytime_cloudy
python -m preprocess_hanhwa.daytime_foggy
python -m preprocess_hanhwa.daytime_overcast
python -m preprocess_hanhwa.daytime_rainy
python -m preprocess_hanhwa.night_clear
python -m preprocess_hanhwa.night_foggy
python -m preprocess_hanhwa.night_rainy
python -m preprocess_hanhwa.scenario1
python -m preprocess_hanhwa.scenario2
python -m preprocess_hanhwa.scenario3
python -m preprocess_hanhwa.scenario4
python -m preprocess_hanhwa.scenario5